name: dartalog
version: 0.3.0
description: Library management application
author: Matthew Barbour <sanmadjack@gmail.com>
homepage: https://github.com/dartalog

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  # analyzer 0.27.3 has a bug with paths on Windows
  analyzer: ^0.29.0
  angular2: ^3.0.0-alpha
  angular2_components: any
  args: ^0.13.6
  browser: ^0.10.0
  connection_pool: ^0.1.2
  crypt: ^1.0.2
  crypto: ^1.1.1
  _discoveryapis_commons: ^0.1.3
  discoveryapis_generator: ^0.8.0
  html: ^0.13.0
  http: ^0.11.3
  http_server: ^0.9.6
  image: ^1.1.26
  intl: ^0.14.0
  logging_handlers: ^0.8.0
  meta: ^1.0.5
  mime: ^0.9.3
  mongo_dart: ^0.2.10
  option: ^1.2.0
  options_file: ^0.11.0
  polymer_elements: ^1.0.0-rc.9
  polymer: ^1.0.0-rc.19
  quagga_dart: ^0.0.2
  route_hierarchical: ^0.7.0
  rpc: ^0.5.7
  shelf: ^0.6.5
  shelf_auth: ^0.7.3
  shelf_exception_handler: ^0.1.0
  shelf_route: ^0.14.3
  shelf_rpc: ^0.0.3
  shelf_static: ^0.2.4
  web_components: ^0.12.3
  version: any
dev_dependencies:
  test: ^0.12.20
dependency_overrides:
  uri:
    git: https://github.com/google/uri.dart.git
executables:
  dartalog-server: server
transformers:
- polymer:
    entry_points:
      - web/index.html
      - web/setup/index.html
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives