name: dartalog
description: Angular web client for the dartalog application
version: 0.0.1
#homepage: https://www.example.com
#author: Matthew <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  dartalog_shared:
    path: ../shared

  angular2: ^3.0.0-alpha
  angular2_components: any
  polymer_elements: ^1.0.0-rc.9
  polymer: ^1.0.0-rc.19
  web_components: ^0.12.3
  logging_handlers: ^0.8.0
  option: ^1.2.0
  _discoveryapis_commons: ^0.1.3
  mime: ^0.9.3

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- polymer:
    entry_points:
      - web/index.html
      - web/setup/index.html
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
    - --enable-experimental-mirrors
