name: dartalog
version: 0.3.0
description: Library management application
author: Matthew Barbour <sanmadjack@gmail.com>
homepage: https://github.com/dartalog

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  dartalog_shared:
    path: ../shared
#  args: ^0.13.6
  connection_pool: ^0.1.2
  crypt: ^1.0.2
  http_server: ^0.9.6
  image: ^1.1.26
  di: ^3.0.0
  logging_handlers: ^0.8.0
  meta: ^1.0.5
  mongo_dart: ^0.2.10
  option: ^1.2.0
  options_file: ^0.11.0
  rpc: ^0.5.7
  shelf: ^0.6.5
  shelf_auth: ^0.7.3
  shelf_exception_handler: ^0.1.0
  shelf_route: ^0.14.3
  shelf_rpc: ^0.0.3
  shelf_static: ^0.2.4
#  version: any
dev_dependencies:
  test: any
dependency_overrides:
  uri:
    git: https://github.com/google/uri.dart.git
executables:
  dartalog-server: server
