name: dartalog_shared
description: Shared code between the dartalog server and clients
version: 0.0.1
#author: Matthew <sanmadjack@gmail.com>
environment:
  sdk: '>=1.20.1 <2.0.0'
dependencies:
  uuid: ^0.5.3
  intl: ^0.15.0
dev_dependencies:
  test: ^0.12.0
